jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Git Repo
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Maven Central Repo
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.GPG_SECRET }}
        java-version: 8
        server-id: ossrh
        server-password: OSSRH_PASSWORD
        server-username: OSSRH_USER
    - continue-on-error: true
      name: debug settings.xml
      run: cat /home/runner/.m2/settings.xml
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
      name: Publish to Maven Central Repo
      run: mvn clean deploy --batch-mode --activate-profiles deploy
name: Maven Central Repo Deployment
on:
  repository_dispatch:
    types: trigger-ga___maven-publish.yml
